"""Initial Migration

Revision ID: 0bfb1ade26b4
Revises: 
Create Date: 2022-01-29 21:32:12.132911

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0bfb1ade26b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('user_name', sa.String(length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users')),
                    sa.UniqueConstraint('user_name', name=op.f('uq_Users_user_name'))
                    )
    op.create_table('Entries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('amount_in_cents', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['Users.id'],
                        name=op.f('fk_Entries_user_id_Users'),
                        onupdate='CASCADE',
                        ondelete='CASCADE',
                    ),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_Entries'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Entries')
    op.drop_table('Users')
    # ### end Alembic commands ###
